name: CI/CD Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: echo "No tests available"

      - name: Build Docker image
        run: docker build -t flask-docker-app .
      
      - name: Test Flask App
        run: |
          docker build -t flask-docker-app .
          docker run -d -p 8000:8000 flask-docker-app
          sleep 5
          curl http://localhost:8000/



      